In [18]:
import numpy as np
import pandas as pd
data = pd.read_csv('kerala.csv')
data.describe()

YEAR         JAN         FEB         MAR         APR  \
count   118.000000  118.000000  118.000000  118.000000  118.000000   
mean   1959.500000   12.218644   15.633898   36.670339  110.330508   
std      34.207699   15.473766   16.406290   30.063862   44.633452   
min    1901.000000    0.000000    0.000000    0.100000   13.100000   
25%    1930.250000    2.175000    4.700000   18.100000   74.350000   
50%    1959.500000    5.800000    8.350000   28.400000  110.400000   
75%    1988.750000   18.175000   21.400000   49.825000  136.450000   
max    2018.000000   83.500000   79.000000  217.200000  238.000000   

              MAY          JUN          JUL          AUG         SEP  \
count  118.000000   118.000000   118.000000   118.000000  118.000000   
mean   228.644915   651.617797   698.220339   430.369492  246.207627   
std    147.548778   186.181363   228.988966   181.980463  121.901131   
min     53.400000   196.800000   167.500000   178.600000   41.300000   
25%    125.050000   535.550000   533.200000   316.725000  155.425000   
50%    184.600000   625.600000   691.650000   386.250000  223.550000   
75%    264.875000   786.975000   832.425000   500.100000  334.500000   
max    738.800000  1098.200000  1526.500000  1398.900000  526.700000   

              OCT         NOV         DEC   ANNUAL RAINFALL  
count  118.000000  118.000000  118.000000        118.000000  
mean   293.207627  162.311017   40.009322       2925.405085  
std     93.705253   83.200485   36.676330        452.169407  
min     68.500000   31.500000    0.100000       2068.800000  
25%    222.125000   93.025000   10.350000       2613.525000  
50%    284.300000  152.450000   31.100000       2934.300000  
75%    355.150000  218.325000   54.025000       3170.400000  
max    567.900000  365.600000  202.300000       4473.000000

In [19]:
data['FLOODS'].replace(['YES','NO'],[1,0],inplace=True)

In [20]:
data.head()

SUBDIVISION  YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL    AUG  \
0      KERALA  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0  357.5   
1      KERALA  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0  315.8   
2      KERALA  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5  420.2   
3      KERALA  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5  351.8   
4      KERALA  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5  293.6   

     SEP    OCT    NOV    DEC   ANNUAL RAINFALL  FLOODS  
0  197.7  266.9  350.8   48.4            3248.6       1  
1  491.6  358.4  158.3  121.5            3326.6       1  
2  341.8  354.1  157.0   59.0            3271.2       1  
3  222.7  328.1   33.9    3.3            3129.7       1  
4  217.2  383.5   74.4    0.2            2741.6       0

In [21]:
x = data.iloc[:,1:14]
x.head()

YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL    AUG    SEP    OCT  \
0  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0  357.5  197.7  266.9   
1  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0  315.8  491.6  358.4   
2  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5  420.2  341.8  354.1   
3  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5  351.8  222.7  328.1   
4  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5  293.6  217.2  383.5   

     NOV    DEC  
0  350.8   48.4  
1  158.3  121.5  
2  157.0   59.0  
3   33.9    3.3  
4   74.4    0.2

In [22]:
y = data.iloc[:, -1]
y.head()


0    1
1    1
2    1
3    1
4    0
Name: FLOODS, dtype: int64

In [23]:
from sklearn import preprocessing
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.        , 0.34371257, 0.56582278, ..., 0.39727673, 0.95570189,
        0.2388724 ],
       [0.00854701, 0.08023952, 0.03291139, ..., 0.5804966 , 0.37952709,
        0.60039565],
       [0.01709402, 0.03832335, 0.23544304, ..., 0.57188626, 0.37563604,
        0.29129575],
       ...,
       [0.98290598, 0.02874251, 0.04810127, ..., 0.31517821, 0.28105358,
        0.11622156],
       [0.99145299, 0.02275449, 0.08607595, ..., 0.24809772, 0.18258007,
        0.18793274],
       [1.        , 0.34850299, 0.65949367, ..., 0.57589107, 0.28105358,
        0.3214639 ]])

In [24]:
from sklearn import model_selection,neighbors
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [25]:
x_train.head()

YEAR   JAN   FEB   MAR    APR    MAY     JUN    JUL    AUG    SEP    OCT  \
29   1930  10.8  10.8  39.0  102.7  404.9   633.1  401.7  273.4  411.5  433.9   
8    1909  54.1  11.8  61.3   93.8  473.2   704.7  782.3  258.0  195.4  212.1   
16   1917   2.9  47.6  79.4   38.1  122.9   703.7  342.7  335.1  470.3  264.1   
112  2013   3.9  40.1  49.9   49.3  119.3  1042.7  830.2  369.7  318.6  259.9   
78   1979   2.4  30.0  11.7   42.0  127.7   582.9  662.2  383.7  211.7  163.8   

       NOV   DEC  
29   207.0  89.2  
8    171.1  32.3  
16   256.4  41.6  
112  154.9  17.0  
78   261.7  23.3

In [26]:
y_train.head()

29     1
8      1
16     0
112    1
78     0
Name: FLOODS, dtype: int64

In [27]:
x_train_std = minmax.fit_transform(x_train)
x_test_std = minmax.transform(x_test)

In [28]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr_clf = lr.fit(x_train_std,y_train)

lr_accuracy = cross_val_score(lr_clf,x_test_std,y_test,cv=3,scoring='accuracy',n_jobs=-1)

In [29]:
lr_accuracy.mean()

0.8333333333333334

In [33]:
y_pred = lr_clf.predict(x_test_std)
print('Predicted chances of flood')
print(y_predict)

Predicted chances of flood
[1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1]


In [34]:
print('Actual chances of flood')
print(y_test.values)

Actual chances of flood
[1 0 0 1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1]


In [35]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\naccuracy score:%f"%(accuracy_score(y_test,y_pred)*100))
print("recall score:%f"%(recall_score(y_test,y_pred)*100))
print("roc score:%f"%(roc_auc_score(y_test,y_pred)*100))



accuracy score:83.333333
recall score:69.230769
roc score:84.615385
